const fontFamily = {
    PoppinsBlack: 'Poppins-Black',
    PoppinsBlackItalic: 'Poppins-BlackItalic',
    PoppinsBold: 'Poppins-Bold',
    PoppinsBoldItalic: 'Poppins-BoldItalic',
    PoppinsExtraBold: 'Poppins-ExtraBold',
    PoppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
    PoppinsExtraLight: 'Poppins-ExtraLight',
    PoppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
    PoppinsItalic: 'Poppins-Italic',
    PoppinsLight: 'Poppins-Light',
    PoppinsLightItalic: 'Poppins-LightItalic',
    PoppinsMedium: 'Poppins-Medium',
    PoppinsMediumItalic: 'Poppins-MediumItalic',
    PoppinsRegular: 'Poppins-Regular',
    PoppinsSemiBold: 'Poppins-SemiBold',
    PoppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
    PoppinsThin: 'Poppins-Thin',
    PoppinsThinItalic: 'Poppins-ThinItalic',
    LatoBlack: 'Lato-Black',
    LatoBlackItalic: 'Lato-BlackItalic',
    LatoBold: 'Lato-Bold',
    LatoBoldItalic: 'Lato-BoldItalic',
    LatoItalic: 'Lato-Italic',
    LatoLight: 'Lato-Light',
    LatoLightItalic: 'Lato-LightItalic',
    LatoRegular: 'Lato-Regular',
    LatoThin: 'Lato-Thin',
    LatoThinItalic: 'Lato-ThinItalic',
    NunitoBlack: 'Nunito-Black',
    NunitoBlackItalic: 'Nunito-BlackItalic',
    NunitoBold: 'Nunito-Bold',
    NunitoBoldItalic: 'Nunito-BoldItalic',
    NunitoExtraBold: 'Nunito-ExtraBold',
    NunitoExtraBoldItalic: 'Nunito-ExtraBoldItalic',
    NunitoExtraLight: 'Nunito-ExtraLight',
    NunitoExtraLightItalic: 'Nunito-ExtraLightItalic',
    NunitoItalic: 'Nunito-Italic',
    NunitoLight: 'Nunito-Light',
    NunitoLightItalic: 'Nunito-LightItalic',
    NunitoMedium: 'Nunito-Medium',
    NunitoMediumItalic: 'Nunito-MediumItalic',
    NunitoRegular: 'Nunito-Regular',
    NunitoSemiBold: 'Nunito-SemiBold',
    NunitoSemiBoldItalic: 'Nunito-SemiBoldItalic',
}

export { fontFamily }